# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p9Kt3I7_Y-iQEHdIzzD0greXyGD8EkSu
"""

from sentence_transformers import SentenceTransformer

model = SentenceTransformer('all-MiniLM-L6-v2')  # A lightweight, efficient model

s="The California three-judge court ruled that the Bank Merger Act of 1966 is the controlling statute for bank mergers. The court held that the Department of Justice was not required to base its case on violations of Section 7 of the Clayton Act and that the 1966 Act did not significantly alter the substantive antitrust standards previously used in evaluating bank mergers. The decision emphasized that the Clayton Act was not necessary for the plaintiff's case as the Bank Merger Act was sufficient and applicable."



d="The California three-judge court disagreed with the Department of Justice's stance, ruling that the Bank Merger Act of 1966 had indeed made substantial changes to the substantive law and the standards that should be applied to bank mergers."


sentences = [s, d]

embeddings = model.encode(sentences)

from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity([embeddings[0]], [embeddings[1]])
print(f"Cosine Similarity: {similarity[0][0]:.2f}")
print(type(similarity[0][0]))
print(similarity)

import json

data = []

with open('/content/generated_answer.json','r') as file:
  data = json.load(file)

  for entry in data:
    embeddings = model.encode([entry['answer'],entry['generated']])
    before = entry['cosine_similarity']
    entry['cosine_similarity'] = round(float(cosine_similarity([embeddings[0]], [embeddings[1]])[0][0]), 3)
    print(f'Before: {before} After: {entry["cosine_similarity"]}')

with open('/content/generated_answer.json','w') as file:
  json.dump(data,file,indent=4)